services:
  - type: web
    name: gentax-ai
    env: python
    plan: free
  
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn GENTAX-AI.gentaxai.main:app --host 0.0.0.0 --port $PORT"

    runtime:
      python:
        version: "3.12.3"

    autoDeploy: true

    region: oregon
